name: ci

on:
  pull_request:
    branches:
    - main
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint ${{ matrix.ruby }}

    strategy:
      matrix:
        ruby:
          - 2.5

      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"

      - name: Install Dependencies
        shell: bash -l -e -o pipefail {0}
        run: |
          rm -f Gemfile.lock
          bundle install --jobs=3 && bundle update --jobs=3

      - name: Run Linter
        shell: bash -l -e -o pipefail {0}
        run: |
          CI=true bundle exec standardrb

  test-ffi:
    runs-on: ubuntu-latest

    name: Test FFI ${{ matrix.ruby }}

    strategy:
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
          - 3.4

      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"

      - name: Install Dependencies
        shell: bash -l -e -o pipefail {0}
        run: |
          rm -f Gemfile.lock
          bundle install --jobs=3 && bundle update --jobs=3

      - name: Install FFI Dependencies
        shell: bash -l -e -o pipefail {0}
        working-directory: ./ffi
        run: |
          rm -f Gemfile.lock
          bundle install --jobs=3 && bundle update --jobs=3

      - name: Run FFI Tests
        shell: bash -l -e -o pipefail {0}
        working-directory: ./ffi
        run: |
          CI=true bundle exec rake test

  test-mri:
    runs-on: ubuntu-latest

    name: Test MRI ${{ matrix.ruby }}

    strategy:
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
          - 3.4

      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"

      - name: Install Dependencies
        shell: bash -l -e -o pipefail {0}
        run: |
          rm -f Gemfile.lock
          bundle install --jobs=3 && bundle update --jobs=3

      - name: Install MRI Dependencies
        shell: bash -l -e -o pipefail {0}
        working-directory: ./mri
        run: |
          rm -f Gemfile.lock
          bundle install --jobs=3 && bundle update --jobs=3

      - name: Run MRI Tests
        shell: bash -l -e -o pipefail {0}
        working-directory: ./mri
        run: |
          CI=true bundle exec rake test
